version: "3"
services:
  web:
    dockerfile: Dockerfile-dev
    build: .
    image: freeformpdx/kffpadmin
    volumes:
      - .:/opt/app
      - /opt/app/node_modules

    ports:
      - "3000:3000"
    links:
      - db
    environment:
      NODE_ENV: development
    command: yarn dev
    depends_on:
        - db
  db:
    image: mongo
    ports:
      - "27017:27017"
